-- DidAlexWin / Supabase schema
-- Separate namespace for the Eala site. Nothing here is used by BBD/Hamza.

create extension if not exists http with schema extensions;

create table if not exists public.eala_player (
  player_id bigint primary key,
  name text not null,
  slug text,
  country text,
  date_of_birth date,
  height_cm integer,
  handedness text,
  prize_money numeric,
  active boolean,
  profile_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.eala_matches (
  event_id bigint primary key,
  player_id bigint not null references public.eala_player(player_id),
  match_date date,
  match_start timestamptz,
  status text,
  category text not null check (category in ('singles', 'doubles', 'unknown')),
  tournament_name text,
  tournament_slug text,
  tournament_id bigint,
  season_name text,
  season_id bigint,
  round_name text,
  round_number integer,
  surface text,
  winner_side text check (winner_side in ('home', 'away', 'unknown')),
  eala_side text check (eala_side in ('home', 'away', 'unknown')),
  eala_won boolean,
  home_players jsonb not null default '[]'::jsonb,
  away_players jsonb not null default '[]'::jsonb,
  set_scores jsonb not null default '[]'::jsonb,
  duration_seconds integer,
  custom_id text,
  raw_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists idx_eala_matches_player_start
  on public.eala_matches (player_id, match_start desc);

create index if not exists idx_eala_matches_category_start
  on public.eala_matches (category, match_start desc);

create table if not exists public.eala_rankings (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.eala_player(player_id),
  ranking_type text not null check (ranking_type in ('singles', 'doubles', 'unknown')),
  ranking integer,
  ranking_date date,
  raw_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists idx_eala_rankings_player_type_date
  on public.eala_rankings (player_id, ranking_type, ranking_date desc);

create unique index if not exists ux_eala_rankings_player_type_date
  on public.eala_rankings (player_id, ranking_type, ranking_date);

create table if not exists public.eala_stats (
  player_id bigint primary key references public.eala_player(player_id),
  singles_wins integer,
  singles_losses integer,
  doubles_wins integer,
  doubles_losses integer,
  singles_titles integer,
  doubles_titles integer,
  highest_singles_ranking integer,
  highest_doubles_ranking integer,
  grand_slam_singles jsonb not null default '{}'::jsonb,
  grand_slam_doubles jsonb not null default '{}'::jsonb,
  raw_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- We use service-role access server-side only.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY to the browser.


create table if not exists public.eala_next_match (
  player_id bigint primary key references public.eala_player(player_id),
  tournament text not null,
  round_name text,
  opponent text,
  match_start timestamptz,
  surface text,
  venue text,
  tournament_start timestamptz,
  tournament_end timestamptz,
  source_event_id bigint references public.eala_matches(event_id),
  raw_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.eala_sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  success boolean not null default false,
  matches_singles integer not null default 0,
  matches_doubles integer not null default 0,
  rankings_updated integer not null default 0,
  next_match_found boolean not null default false,
  error_message text
);

alter table public.eala_player enable row level security;
alter table public.eala_matches enable row level security;
alter table public.eala_rankings enable row level security;
alter table public.eala_stats enable row level security;
alter table public.eala_next_match enable row level security;
alter table public.eala_sync_runs enable row level security;

drop policy if exists eala_player_public_read on public.eala_player;
create policy eala_player_public_read on public.eala_player
  for select to anon, authenticated using (true);

drop policy if exists eala_matches_public_read on public.eala_matches;
create policy eala_matches_public_read on public.eala_matches
  for select to anon, authenticated using (true);

drop policy if exists eala_rankings_public_read on public.eala_rankings;
create policy eala_rankings_public_read on public.eala_rankings
  for select to anon, authenticated using (true);

drop policy if exists eala_stats_public_read on public.eala_stats;
create policy eala_stats_public_read on public.eala_stats
  for select to anon, authenticated using (true);

drop policy if exists eala_next_match_public_read on public.eala_next_match;
create policy eala_next_match_public_read on public.eala_next_match
  for select to anon, authenticated using (true);

grant select on public.eala_player to anon, authenticated;
grant select on public.eala_matches to anon, authenticated;
grant select on public.eala_rankings to anon, authenticated;
grant select on public.eala_stats to anon, authenticated;
grant select on public.eala_next_match to anon, authenticated;

-- WTA writes are performed by the private sync-eala Edge Function.
-- The public site has read-only access through the Data API.
