-- DidAlexWin / Supabase schema
-- Separate namespace for the Eala site. Nothing here is used by BBD/Hamza.

create table if not exists public.eala_player (
  player_id bigint primary key,
  name text not null,
  slug text,
  country text,
  date_of_birth date,
  height_cm integer,
  handedness text,
  prize_money numeric,
  active boolean,
  profile_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.eala_matches (
  event_id bigint primary key,
  player_id bigint not null references public.eala_player(player_id),
  match_start timestamptz,
  status text,
  category text not null check (category in ('singles', 'doubles', 'unknown')),
  tournament_name text,
  tournament_slug text,
  tournament_id bigint,
  season_name text,
  season_id bigint,
  round_name text,
  round_number integer,
  surface text,
  winner_side text check (winner_side in ('home', 'away', 'unknown')),
  eala_side text check (eala_side in ('home', 'away', 'unknown')),
  eala_won boolean,
  home_players jsonb not null default '[]'::jsonb,
  away_players jsonb not null default '[]'::jsonb,
  set_scores jsonb not null default '[]'::jsonb,
  duration_seconds integer,
  custom_id text,
  raw_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists idx_eala_matches_player_start
  on public.eala_matches (player_id, match_start desc);

create index if not exists idx_eala_matches_category_start
  on public.eala_matches (category, match_start desc);

create table if not exists public.eala_rankings (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.eala_player(player_id),
  ranking_type text not null check (ranking_type in ('singles', 'doubles', 'unknown')),
  ranking integer,
  ranking_date date,
  raw_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists idx_eala_rankings_player_type_date
  on public.eala_rankings (player_id, ranking_type, ranking_date desc);

create table if not exists public.eala_stats (
  player_id bigint primary key references public.eala_player(player_id),
  singles_wins integer,
  singles_losses integer,
  doubles_wins integer,
  doubles_losses integer,
  singles_titles integer,
  doubles_titles integer,
  highest_singles_ranking integer,
  highest_doubles_ranking integer,
  grand_slam_singles jsonb not null default '{}'::jsonb,
  grand_slam_doubles jsonb not null default '{}'::jsonb,
  raw_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- We use service-role access server-side only.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY to the browser.
